# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dota2ComedicStats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dota2ComedicStats

  target 'Dota2ComedicStatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dota2ComedicStatsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
